[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "pip3 install --break-system-packages -r python/requirements.txt"
]

[phases.build]
cmds = ["pnpm -r build"]
