import type { PortfolioState } from './market.js';

// Signal action types
export type SignalAction = 'BUY' | 'SELL' | 'HOLD' | 'REBALANCE';

// Supported LLM providers
export type LlmProvider = 'anthropic' | 'openai' | 'gemini' | 'deepseek' | 'ollama';

// Signal generated by a Python strategy
export interface StrategySignal {
  strategyId: string;
  action: SignalAction;
  token: string;
  amountUsd?: number;
  targetPrice?: number;
  confidence: number;          // 0.0 - 1.0
  rationale: string;
  requiresAiApproval: boolean;
}

// Batch of signals returned from Python IPC
export interface SignalBatch {
  cycleId: string;
  timestamp: string;
  signals: StrategySignal[];
  riskVetoed: boolean;
  vetoReason?: string;
}

// Unified AI decision (provider-agnostic)
export interface AiDecision {
  approved: boolean;
  adjustedAmountUsd?: number;
  reasoning: string;
  confidence: number;
  timestamp: string;
  provider: LlmProvider;
  model: string;
}

// Final approved decision ready for execution
export interface ApprovedDecision {
  signal: StrategySignal;
  approvedBy: 'auto' | 'ai';
  finalAmountUsd: number;
  aiDecision?: AiDecision;
}

// Strategy config shape loaded from YAML
export interface StrategyConfig {
  id: string;
  enabled: boolean;
  configFile: string;
  schedule: string;
}

// Agent memory entry (rolling log for AI context)
export interface AgentMemoryEntry {
  timestamp: string;
  type: 'decision' | 'trade' | 'veto' | 'error';
  summary: string;
  data?: Record<string, unknown>;
}
